config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/search', to: 'search#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member
  attr_reader :id, :name, :role, :house

  def initialize(member)
    @id = member[:_id]
    @name = member[:name]
    @role = member[:role]
    @house = member[:house]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @facade = HarryPotterFacade.new(params[:house])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def hogwarts_houses
    [
      ['Gryffindor', 'Gryffindor'],
      ['Ravenclaw', 'Ravenclaw'],
      ['Slytherin', 'Slytherin'],
      ['Hufflepuff', 'Hufflepuff'],
    ]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Order of The Phoenix</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default" role="navigation">
      <div class="navbar-header">
        <p class ="navbar-brand">The Order of The Phoenix</p>
        <p class="subtitle">Search For Members of The Order of The Phoenix By House</p>
      </div>
      <div class="harry-potter-container">
        <%= image_tag("harry-potter.png", class: "harry-potter") %>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <%= form_tag(search_path, method: "get") do %>
            <%= select_tag(:house, options_for_select(hogwarts_houses), {class: "select-field"}) %>
            <%= submit_tag('Search For Members', class: "button") %>
          <% end %>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/search/index.html.erb
<h1> Members </h1>
<% @facade.members.each do |member| %>
  <p> Name: <%= member.name %> </p>
  <p> Role: <%= member.role %> </p>
  <p> House: <%= member.house %> </p>
  <br>
<% end %>